
version: '3.0'
services:
  web:
    image: "oreganko/io-lab-docker-ci-public:v1.0"
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc4-alpine
    volumes:
      - "redis-data:/data"
volumes:
  redis-data:

